### ISSUE TITLE
Add Local Storage Support

### ISSUE THREAD

**Issue by mattmillerNASM** [SmartTeleMax/MaSha#45]
Is there a way to add browser local storage so when the page is closed and reopened all highlights will remain?

**Comment by Harut** [comment]
MaSha is designed to share highlighted text by saving a highlight in the URL, not to store it locally. I.e. the only "source of truth" is in the current URL.

However, you can hook default behaviour by defining your own options.location object:

``` javascript
const MyLocationHandler = function() {}
MyLocationHandler.prototype = Object.assign({}, MaSha.LocationHandler.prototype, {
  setHash: function(hash) {
    window.location.hash = hash; // default behaviour
    saveToLocalStorage(hash);
  },
  getHash: function() {
    return window.location.hash || getFromLocalStorage();
  }
});
new MaSha({ ...options, location: new MyLocationHandler() });
```

**Comment by ods** [comment]
What about adding this example to documentation of API? But I'd rather use saving to local storage _instead of_ changing URL, not in addition to.
